# Generated by Django 4.2.4 on 2023-08-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='skinstyle',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Original', 'Normal'), ('Anime', 'Anime')], default='Original', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='datecomplete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, default='En espera...', max_length=100),
        ),
    ]
