# Generated by Django 4.2.4 on 2023-08-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orders_skinstyle_alter_orders_datecomplete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='size',
            field=models.FloatField(blank=True, default=0, help_text='Centimetros', null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='skinstyle',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Original', 'Original'), ('Anime', 'Anime')], default='Original', max_length=50),
        ),
    ]
