# Generated by Django 4.2.4 on 2023-08-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_orders_size_alter_orders_skinstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(blank=True, default=1, help_text='Cantidad de unidades', null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='description',
            field=models.TextField(blank=True, help_text='Especifica detalles o modificaciones especiales no especificados anteriormente'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='size',
            field=models.FloatField(blank=True, default=0, help_text='cm', null=True),
        ),
    ]
