# Generated by Django 4.2.4 on 2023-08-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_orders_amount_alter_orders_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='amount',
            new_name='units',
        ),
    ]
